#!/bin/sh

ver=`awk '{print $3}' VERSION`
user=${SF_NAME:LOGNAME}

dir=cricket-$ver
tar=$dir.tar
tgz=$tar.gz

cd /tmp

if [ -d $dir ]; then
	echo "Directory /tmp/$dir exists. Please remove it."
	exit
fi

# we only make releases out of the 1_0_x branch right now
branch="-r v_1_0_x"

echo "Checking out the source..."
cvs -d $user@cvs.cricket.sourceforge.net:/cvsroot/cricket \
	co -d cricket-$ver $branch cricket
# > /dev/null 2>&1

echo "Creating tar.gz package: "

echo "    tar..."
tar cf $tar $dir

echo "    gzip..."
gzip -9 $tar

rm -rf $dir
